#lang racket

(require minikanren/numbers)
(require "helper.rkt")
(require "functions.rkt")
(provide examples)

(define-syntax functions
  (syntax-rules ()
    [(_ f ...) `((,(symbol-trim-last 'f) . ,f) ...)]))

(define examples
  `(("reverse" (foldlEmpty (flip cons))
               ,(functions foldlEmptyf)
               (list char)
               (,(string-c "hello"))
               ,(string-v "olleh"))
    ("append" (flip (foldr cons))
              ,(functions foldrf)
              (list char)
              (,(string-c "hello ") ,(string-c "world"))
              ,(string-v "hello world"))
    ("concat" (foldrEmpty (flip (foldr cons)))
              ,(functions foldrEmptyf foldrf)
              (list char)
              (,(list-c "hello" " " "world"))
              ,(string-v "hello world"))
    ("sum" (foldl add 0) ,(functions foldlf) int (,(list-c 1 2 3)) ,(build-num 6))
    ("adds" (compose map add)
            ,(functions mapf)
            (list int)
            ((num ,(build-num 5)) ,(list-c 1 2 3))
            ,(list-v 6 7 8))
    ("length" (foldr0 (const (add 1))) ,(functions foldr0f) int (,(string-c "123")) ,(build-num 3))
    ("rember" (compose filter neq)
              ,(functions filterf)
              (list char)
              ((char #\o) ,(string-c "hello"))
              ,(string-v "hell"))
    ("maximize" (foldr1 max) ,(functions foldr1f) int (,(list-c 1 2 3 2 1)) ,(build-num 3))
    ("minimize" (foldr1 min) ,(functions foldr1f) int (,(list-c 3 2 5 2 3)) ,(build-num 2))
    ("uniq" (foldrEmpty (fork cons (compose filter neq)))
            ,(functions foldrEmptyf filterf)
            (list char)
            (,(string-c "aaabbc"))
            ,(string-v "abc"))
    ("last" (foldr1 (flip const)) ,(functions foldr1f) char (,(string-c "hello")) (char #\o))))
